Repository 2024-Techeer-Summer-Bootcamp-Team-D/MVStudio-Docker, pull requests merged in 2024-07, with the labels that each got.

#6 [chore] flower RabbitMQ healthy check 적용
  docker-compose-dev.yml
  docker-compose-prod.yml
Labels: 🧭 Chore

#12 [build] Github Actions를 통한 EC2 배포 자동화 구현
  .github/workflows/deploy.yml
Labels: ⛑️ Build

#16 [feat] HTTPS 적용 및 SSL 인증서 발급
  .github/workflows/deploy.yml
  docker-compose-prod.yml
  init-letsencrypt.sh
  nginx/nginx.conf
Labels: 🚀 Feat

#22 [chore] prometheus, grafana 세팅
  .gitignore
  alertmanager/alertmanager.yml
  docker-compose-monitoring.yml
  nginx/nginx.conf
  prometheus/alert-rules.yml
  prometheus/prometheus.yml
Labels: 🧭 Chore
